# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{delayed_job_ironmq}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Shapiotko", "Iron.io, Inc"]
  s.date = %q{2013-03-22}
  s.description = %q{IronMQ backend for delayed_job}
  s.email = %q{info@iron.io}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "VERSION",
    "lib/delayed/backend/actions.rb",
    "lib/delayed/backend/iron_mq_config.rb",
    "lib/delayed/backend/ironmq.rb",
    "lib/delayed/backend/version.rb",
    "lib/delayed/backend/worker.rb",
    "lib/delayed/serialization/ironmq.rb",
    "lib/delayed_job_ironmq.rb",
    "spec/.gitkeep"
  ]
  s.homepage = %q{https://github.com/thousandsofthem/delayed_job_ironmq}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{IronMQ backend for delayed_job}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<iron_mq>, [">= 4.0.0"])
      s.add_runtime_dependency(%q<delayed_job>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
      s.add_development_dependency(%q<jeweler2>, [">= 0"])
    else
      s.add_dependency(%q<iron_mq>, [">= 4.0.0"])
      s.add_dependency(%q<delayed_job>, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0"])
      s.add_dependency(%q<jeweler2>, [">= 0"])
    end
  else
    s.add_dependency(%q<iron_mq>, [">= 4.0.0"])
    s.add_dependency(%q<delayed_job>, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0"])
    s.add_dependency(%q<jeweler2>, [">= 0"])
  end
end

